site_name: My Blog
nav:
  - Home: first-post.md
  - Blog Index: index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - instant
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.tabs.pills
    - content.code.annotate
    - content.code.copy
    - content.code.fold
    - content.code.highlight
    - content.code.line_numbers
    - content.code.title
    - content.code.wrap
    - content.footnotes
    - content.heading.anchor
    - content.heading.collapse
    - content.heading.permalink
    - content.heading.toc
    - content.image.caption
    - content.image.lightbox
    - content.image.zoom
    - content.link.icon
    - content.link.title
    - content.link.tooltip
    - content.list.collapse
    - content.list.icon
    - content.list.link
    - content.list.number
    - content.list.title
    - content.list.tooltip
    - content.math
    - content.table.collapse
    - content.table.icon
    - content.table.link
    - content.table.number
    - content.table.title
    - content.table.tooltip
    - content.tabs
    - content.tabs.link
    - content.tabs.pills
    - content.tabs.tooltip
    - content.text.align
    - content.text.break
    - content.text.color
    - content.text.highlight
    - content.text.italic
    - content.text.link
    - content.text.monospace
    - content.text.small
    - content.text.strikethrough
    - content.text.subscript
    - content.text.superscript
    - content.text.underline
    - content.text.uppercase
    - content.text.wrap
    - content.video
    - content.video.caption
    - content.video.lightbox
    - content.video.zoom
    - content.widget
    - content.widget.icon
    - content.widget.link
    - content.widget.title
    - content.widget.tooltip
    - content.widget.wrap
    - content.widget.zoom
    - content.widget.lightbox
    - content.widget.caption
    - content.widget.video
    - content.widget.image
    - content.widget.text
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.widget.code
    - content.widget.math
    - content.widget.footnotes
    - content.widget.heading
    - content.widget.link
    - content.widget.text
    - content.widget.video
    - content.widget.image
    - content.widget.list
    - content.widget.table
    - content.widget.tabs
    - content.code.annotate
    - content.code.copy
    - content.code.fold
    - content.code.highlight
    - content.code.line_numbers
    - content.code.title
    - content.code.wrap
    - content.footnotes
    - content.heading.anchor
    - content.heading.collapse
    - content.heading.permalink
    - content.heading.toc
    - content.image.caption
    - content.image.lightbox
    - content.image.zoom
